theme: jekyll-theme-cayman
title: Subodh Mishra
description: "Research and Personal Webpage"

# Social icons
github_username: SubMishMar
reddit_username:
bitbucket_username:
stackoverflow_id:
twitter_username: 
skype_username:
steam_nickname:
google_plus_id:
linkedin_username: subodh-mishra
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:
telegram_username:
vk_id:
