theme: jekyll-theme-cayman
title: Subodh Mishra
description: "विद्या ददाति विनयं विनयाद् याति पात्रताम्। पात्रत्वाद्धनमाप्नोति धनाद्धर्मं ततः सुखम्॥ "
text-align: justify

# Social icons
github_username: SubMishMar
reddit_username:
bitbucket_username:
stackoverflow_id:
twitter_username: 
skype_username:
steam_nickname:
google_plus_id:
linkedin_username: subodh-mishra
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:
telegram_username:
vk_id:
